### ISSUE TITLE
You should add some images to the CurseForge page.

### ISSUE THREAD

**Issue by K0-RR** [spacegoat3/BlockOf#3]
Also, I noticed you are recommending other more blocks mods, what about this one? https://www.curseforge.com/minecraft/mc-mods/mbm-more-blocks-mod

**Comment by spacegoat3** [comment]
1 - There are some images in the description. You can see them by opening the "Spoilers" on the [**CurseForge Page**](https://www.curseforge.com/minecraft/mc-mods/block-of).  But I will add some images of the blocks.

2 - I recommended mods with similar features but why not, I will add it.

Thank you for your feedback :D
